version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: medical
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:pass@db:5432/medical
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
